### ISSUE TITLE
Hurray for you!

### ISSUE THREAD

**Issue by synthesizerpatel** [apparentlymart/go-openvpn-mgmt#1]
I've been wanting to do this for a while and you beat me to it and did it better than I would have. 

Thanks for your effort. With any luck I'll have some improvements to PR you with. 

Also, apologies for opening an issue for this.. couldn't find any other way to let you know how much I appreciated it.

**Comment by apparentlymart** [comment]
Hi @synthesizerpatel. Thanks for the interest!

My motivation for writing this is [another project I'm working on](https://github.com/defgrid/openvpn-peer) that will use OpenVPN to automatically establish VPN tunnels between private networks. So far I've mainly implemented only the functionality I need for that, but I'd love it if you or other people would be interested in helping to expand to other use-cases.
